sampling:
  rate: 100
  duration: 1
heart_rate:
  min: 60
  max: 100
  amplitude: 1
variability_factors:
  breathing: 0.2
  activity: 0.3
  stress: 0.1
  age: 0.05
filter:
  cutoff_freq: 20
location:
  latitude: 37.7749
  longitude: -122.4194
  delta_lat: 0.00001
  delta_long: 0.00001
